# Generated by Django 4.1.7 on 2023-03-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_order_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='api.cart', verbose_name='Продукты'),
        ),
    ]
